### ISSUE TITLE
It doesn't work properly !

### ISSUE THREAD

**Issue by dr1361teh** [vatsimgoodies/vatsim-real-ops#1]
I have installed and migrated this app. but get following error for the home page.
"Sorry, the page you are looking for could not be found. "
any suggestion ?

**Comment by roelgonzalez** [comment]
Hi @dr1361teh glad to see your interest in the project. As of now the project is still a work-in-progress, meaning that it is not ready for use yet. I will try and make it more clear in the readme. For now I suggest you follow the project so you can stay up to date, and also feel free to message me if you have any questions.

**Comment by GeorgeBarlow** [comment]
Do you have an eta?

Thanks :)

**Comment by roelgonzalez** [comment]
@dr1361teh @GeorgeBarlow I know it's been quite some months since the last contact, but I thought I'd give an update.
I am actively working on the development of the project at the moment. I am not sure exactly how long it will take, because obviously it depends greatly on what hurdles I encounter. I am however striving to have a working product within 30 days or so. If there are any questions or requests, feel free to let me know and we can discuss it.

**Comment by roelgonzalez** [comment]
The current ETA is March.

**Comment by roelgonzalez** [comment]
It has been released.
